makefile, touch, file class, circleci config update
Teaching-projects/SZE-MoSzE-2019-GatewayTimeoutError pull request #5
Opened 2019-10-15 18:53 UTC by lebbenszki

Made a makefile, edited CircleCi config file, working touch command.

2019-10-16 00:45 UTC, hegyhati requested changes
@lebbenszki a CI configba keruljon bele olyan step is, ami futtatja az elkeszult binarist es i/o teszteli 2-3 peldan.

2019-10-16 00:46 UTC, hegyhati commented
@wajzy a CI cofig / make dolgot nezem en (make rendben amugy), magat a kodot kerlek valamikor vizslasd meg.

2019-10-19 17:15 UTC, wajzy requested changes
Mivel a fájloknak és a könyvtáraknak vannak közös tulajdonságaik (név, szülő könyvtár) és ezekhez kapcsolódó funkcióik, javaslom egy közös ősből örököltetni ezeket a közös képességeket.

2019-10-19 17:15 UTC, wajzy commented on directory.cpp
>  void directory::print()
Ez is lehetne const tagfüggvény, de ennyi erővel ezt az egy sor kódot át is lehetne tenni az ls-be, vagy fordítva

2019-10-19 17:15 UTC, wajzy commented on directory.h
>      list <directory*> subdirectories;
Megfontolnám a map használatát, ha a bejegyzések nevétől elvárjuk, hogy egyedi legyen

2019-10-19 17:15 UTC, wajzy commented on directory.h
> +    list <file*> files;
Lehet azonos nevű fájl és mappa egy mappában a külön tárolók miatt

2019-10-19 17:15 UTC, wajzy commented on directory.h
>      void segedrmrf();
Ennek feltétlenül nyilvánosnak kell lennie?

2019-10-19 17:15 UTC, wajzy commented on filesystem.cpp
> +int filesystem::touch(string filename){
A függvény nem ad hibaüzeneteket.

2019-10-19 17:15 UTC, wajzy commented on filesystem.cpp
> +    path.push_front(currentdir->getName());
Miért kell, hogy a path adattag legyen? Miért nem lehet lokális változó?

2019-10-19 17:15 UTC, wajzy commented on filesystem.cpp
> +    if(tmp==0){
Nem értem, minek kell a tmp. Ha értéke 1, akkor el sem jut ide a vezérlés a fenti return miatt.

2019-10-19 17:15 UTC, wajzy commented on filesystem.cpp
>             else std::cout<<"Unknown command"<<std::endl;
Ez a quit-re is kiírja, hogy Unknown command. De egyébként miért nem exit?

2019-10-19 17:15 UTC, wajzy commented on filesystem.h
>      list <directory*> directories;
Ez mihez kell?

2019-11-11 20:38 UTC, lebbenszki commented
@hegyhati CircleCi config nem let átírva mert a többi parancsal együtt írtuk meg a tesztet csak feldaraboltuk hogy ne egy branchbe legyen feltöltve az egész.

2019-11-12 07:43 UTC, hegyhati commented
@wajzy kerlek nezd meg, hogy mindent megcsinaltak-e, amit kellett.

@lebbenszki Azert ne uljetek forditva a lovon. Ne csinaljatok meg egyben, aztan szedjetek szet branchekre, annak semmi ertelme. Direkt azert vannak kulon branchek, hogy azok egymastol fuggetlenul menjenek, ahogy a valosagban is tortenne, Es ha jonnek elo conflictok,azokat fel kelljen oldani.

2019-11-21 13:03 UTC, closed without merging