Absolutepath
Teaching-projects/SZE-MoSzE-2019-GatewayTimeoutError pull request #6
Opened 2019-11-11 21:12 UTC by szerdahelyir

absolutepath done

2019-11-18 09:46 UTC, wajzy requested changes
Ez a dynamiccast-os trükk nyilván működik az ősosztályt címző mutató által kijelölt objektum típusának ellenőrzésére, de nem tudom, mennyire hatékony megoldást jelent. Én valószínűleg inkább készítettem volna egy bool isFile()-szerű tagfüggvényt az ősbe, ami az egyik leszármazottban igazzal, a másikban hamissal tér vissza. 
Ami az abszolút elérési utakat illeti, az ránézésre megvan, de a sok redundáns részt mindenképpen el kellene tüntetni.

2019-11-18 09:46 UTC, wajzy commented on ancestor.cpp
> +ancestor::ancestor(string name, directory* parent)
Nem túl kifejező ez a név, bár valóban két osztály közös őse. Arra kellene utalni, hogy ez egy tetszőleges fájlrendszerbeli bejegyzést takarhat. Pl. item, vagy hasonló.

2019-11-18 09:46 UTC, wajzy commented on ancestor.h
> +    virtual string getname()=0;
A getname, getparent tagfüggvényeket nem lehetne a közös ősben definiálni? Hirtelen nem látom, miben fog a két leszármazott működése eltérni egymástól.

2019-11-18 09:46 UTC, wajzy commented on directory.cpp
> +list<ancestor *> directory::getSubdirectories() const
Ez a függvénynév is félrevezető, mert a fájlbejegyzések is a visszaadott értékek között szerepelnek, nem csak a könyvtárak.

2019-11-18 09:46 UTC, wajzy commented on directory.cpp
> +        directory* temp=dynamic_cast<directory*>(*it);
Ugye nem kizárlólag emiatt kellettek a virtuális függvények az ősbe?

2019-11-18 09:46 UTC, wajzy commented on directory.h
> +    list<ancestor*> subdirectories;
Nem vagyok benne biztos, hogy a lista szerencsés választás. Szerintem egy map-pel gyorsabban meg lehetne találni egy konkrét bejegyzést, pl. törlés esetén.

2019-11-18 09:46 UTC, wajzy commented on file.h
> +    string content;
Mi használja ezt az adattagot?

2019-11-18 09:46 UTC, wajzy commented on filesystem.cpp
> +vector<string> filesystem::split(const string& str, const char& delim)
Lehet, hogy megy ez egyszerűbben is: https://www.geeksforgeeks.org/tokenizing-a-string-cpp/

2019-11-18 09:46 UTC, wajzy commented on filesystem.cpp
> +int filesystem::absolutepathmkdir(string path){
Itt egymás után több függvénynek is az eleje majdnem tökéletesen ugyanaz. Ezeket a redundáns részeket el kellene tüntetni.

2019-11-18 09:46 UTC, wajzy commented on test.txt
> +exit
Ez hogyan teszteli az abszolút elérési útvonalakat?

2019-11-18 12:54 UTC, hegyhati commented
> Ez a dynamiccast-os trükk nyilván működik az ősosztályt címző mutató által kijelölt objektum típusának ellenőrzésére, de nem tudom, mennyire hatékony megoldást jelent. Én valószínűleg inkább készítettem volna egy bool isFile()-szerű tagfüggvényt az ősbe, ami az egyik leszármazottban igazzal, a másikban hamissal tér vissza.

Itt vitatkoznek, szerintem jobb a `dynamic_cast`, az ososztalynak ha nem muszaj, ne tudjon arrol, milyen gyerekei vannak. Szoval szerintem inkabb az maradjon.

2019-11-18 16:41 UTC, szerdahelyir commented
@wajzy külön függvénybe raktam a redundáns tartalmakat ahol lehetett, javítottam a neveken, és a tokenizáló függvényt is lecseréltem, viszont a map helyett bent hagytam a listás megoldást mert minden további funkció(echo, fájlba kimentés)-t listával oldottunk meg

2019-11-20 09:33 UTC, wajzy approved these changes

2019-11-22 08:43 UTC, hegyhati commented
@wajzy egyszer mar approve-oltad, azota felment meg 2 commit (+1 update).  Nezd meg pls, hogy tovabbra is aldasod-e a dolgon.

2019-11-22 08:49 UTC, szerdahelyir commented
@hegyhati csak conflict resolve miatt volt az a 2 commit, változtatások nem történtek

2019-11-22 12:59 UTC, wajzy approved these changes

2019-11-22 15:34 UTC, merged