Echo
Teaching-projects/SZE-MoSzE-2019-GatewayTimeoutError pull request #7
Opened 2019-11-12 17:00 UTC by patrikkocsis

2019-11-13 17:17 UTC, oliverosz requested changes
A minél kisebb commitok elvét nem sikerült tartani. Ebben az "Echo done"-nak nagyon kis része az echo megvalósítása.

A Makefile nem jó, az object fájlok dependency listájában az include-olt header fájlokat is fel kell sorolni.

A `cd ..` és `rm -rf` esetén a `..` és `-rf` az első argumentum, nem a parancs része, direkt van szóközzel elválasztva.

2019-11-13 17:17 UTC, oliverosz commented on directory.cpp
> +list<ancestor *> directory::getSubdirectories() const
Miért kell lemásolni ezt a listát? Jobb lenne referencia szerint átadni.

2019-11-13 17:17 UTC, oliverosz commented on filesystem.cpp
> +                tempfile->setContent(content);
Az egy dolog, hogy a `getSubdirectories()` adja vissza a fájlok listáját is, de ez így megengedi azt is, hogy egy könyvtárba echozzunk szöveget, és akkor elcrashel.

2019-11-19 16:00 UTC, oliverosz requested changes
Látható, hogy az rm, rmrf és segedrmrf függvények nagyon hasonló dolgot csinálnak. A kódduplikációt meg nem szeretjük. Jó lenne ezeket egy függvénybe egyesíteni, aminek egy bool paraméter mondaná meg, hogy a nem üres mappákat is törölje-e ki.

A hibakezelés sem teljesen jó, pl. az rm hibakóddal tér vissza, de az sehol sincs használva. Így most nem ír ki hibát, ha nem létező mappát próbálok törölni.

2019-11-19 16:00 UTC, oliverosz commented on directory.cpp
> +list<ancestor *> &directory::getSubdirectories()
De miért nem `const`ez a függvény? Inkább konstans referenciát kéne visszaadni, és akkor engedi.

2019-11-19 16:00 UTC, oliverosz commented on filesystem.cpp
> +                    i=tempfile;
Erre nincs szükség, ha referencia szerint megy végig az elemeken: `auto &i`. Meg gyorsabb is, mert nem másolja le az elemeket feleslegesen.

2019-11-19 16:00 UTC, oliverosz commented on filesystem.cpp
> +                   cout<<argument2;
Ez a kiírás itt elég megtévesztő. Pl.:
````
cd a
ls
root/a/
   b
   c
cd ..
rm -rf a
ab torolve
c torolve
a torolve
````

2019-11-19 16:00 UTC, oliverosz commented on directory.cpp
> +                    return 1;
Nem iterálunk tovább, hanem visszatérünk a függvényből. Ahogy lentebb egy másik ágban is felesleges a léptetés, meg hibás a komment.

2019-11-19 16:00 UTC, oliverosz commented on directory.cpp
> +                }
Itt sem kell továbbiterálni, mert ugyanazon névvel nem lehet másik fájl/mappa.

És miért is kell ez a rekurzív segedrmrf? Miért nem elég a szülő mappát kitörölni? (Ez most nem költői kérdés, várom rá a választ @Teaching-projects/gatewaytimeouterror )

2019-11-19 16:26 UTC, szerdahelyir commented on directory.cpp
> +                }
@oliverosz amikor nem rekurzívan próbáltuk törölni a szülőmappát, akkor a program lefagyott, amikor pedig rekurzívan a fastruktúra végpontjaival kezdtük a törlést, akkor minden működött rendesen(elvileg)

2019-11-19 16:30 UTC, oliverosz commented on directory.cpp
> +                }
@szerdahelyir A szülő törlését én úgy értem, hogy `subdirectories.erase(i)`, mint ahogy üres mappánál van fentebb, tehát attól nem kéne lefagynia. Ha nem üres a mappa, akkor miért nem lehet ugyanúgy kezelni?

2019-11-19 16:38 UTC, szerdahelyir commented on directory.cpp
> +                }
@oliverosz valóban működik így is 😄  de így nem lesz memóriaszivárgás, hogy abban a mappában voltak még fájlok/alkönyvtárak?

2019-11-19 16:46 UTC, oliverosz commented on directory.cpp
> +                }
@szerdahelyir Kb. ugyanannyi memóriaszivárgás lesz benne, mint a mostaniban. :D A segedrmrf-ben sem látok semmi delete hívást, szóval az ezen nem segít. Csak a listákból törli az elemeket, de azt a lista destruktora automatikusan is megcsinálná, ha a fájlok és könyvtárak destruktálódnának.

2019-11-19 16:52 UTC, szerdahelyir commented on directory.cpp
> +                }
@oliverosz így már világos :DD köszönjük a felvilágosítást, javítjuk a hibákat

2019-11-19 18:09 UTC, oliverosz approved these changes
A conflictokat még ki kell javítani, aztán mergelhető.

2019-11-19 19:36 UTC, szerdahelyir commented
@oliverosz elvileg most már minden conflict javítva lett

2019-11-19 20:13 UTC, oliverosz commented
Ok, @hegyhati tudja bemergelni.

2019-11-19 22:11 UTC, merged