Doxygen
Teaching-projects/SZE-MoSzE-2019-GatewayTimeoutError pull request #9
Opened 2019-12-18 20:52 UTC by lebbenszki

Kommenteltük a headereket.
CircleCi-ben pedig legeneráltuk a doxyfilet aztán abból előállítottuk a html feájlikat és artifactként tároltuk.

2019-12-19 12:27 UTC, hegyhati requested changes

2019-12-19 12:27 UTC, hegyhati commented on .circleci/config.yml
> +              make
make?

2019-12-19 12:27 UTC, hegyhati commented on .circleci/config.yml
> +              doxygen -g Doxyfile;
a Doxyfile az ne ilyenkor legyen generalva, hanem az legyen verziokezelt azokkal a beallitasokkal, amiket Ti szeretnetek.

2019-12-19 12:27 UTC, hegyhati commented on .circleci/config.yml
> +            path: ./html
Ha nem deployoljatok valahova, akkor a latex-es pdf-et is artifactoljatok, vagy csak azt.

2019-12-19 20:06 UTC, hegyhati requested changes

2019-12-19 20:06 UTC, hegyhati commented on .circleci/config.yml
> +            command: make
de nem ertem, minek futtatod a doxygen-es jobban a make-et?

2019-12-19 20:06 UTC, hegyhati commented on .circleci/config.yml
> +            command: make
jah, most latom, hogy ez a build. na, nem, a doxygenes folgokat, meg a buildelest tegyetek kulon jobokba.

2019-12-19 20:19 UTC, hegyhati commented on .circleci/config.yml
> +        steps:
? ez szerintem el fog crashelni

2019-12-19 20:59 UTC, lebbenszki commented
Most jónak kellene lennie. 😅

2019-12-21 22:03 UTC, hegyhati approved these changes

2019-12-21 22:03 UTC, hegyhati commented
Oldjatok fela conflicteket, aztan ez meg bemehet.

2019-12-22 12:06 UTC, merged